services:
  portfolio:
    build: .
    container_name: portfolio_container
    ports:
      - "8001:80"
    env_file:
      - .env
    volumes:
      - ./data:/portfolio/data
      - ./alembic:/portfolio/alembic
    restart: always