services:
  portfolio:
    build: .
    container_name: portfolio_container
    ports:
      - "8001:80"
    volumes:
      - ./app:/code/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 80 --reload
    restart: always
